### ISSUE TITLE
Why not CodeCarbon ?

### ISSUE THREAD

**Issue by benoit-cty** [Capgemini-Invent-France/CarbonAI#20]
Hello,
I'm a contributor of CodeCarbon and I'd like to know why you start this from scratch instead of using and contributing to CodeCarbon ?
What do you thing is missing ? Or do you think we are going in the wrong direction ?
Don't get me wrong, having challengers, like Scaphandre, is good but I really don't get what you do differently from CodeCarbon.

**Comment by Neyri** [comment]
Hello,
Thank you for your comment.
We are indeed aware there are similar packages (such as CodeCarbon or experiment-impact-tracker) allowing to measure the energy consumption of a piece of python code. And we are really pleased to see the subject interests a lot of people and that many datascientists feel concerned about this matter too.
The development of CarbonAI started in february 2020 (as you can see from the commit history), first used internally it was then decided to publish it as open-source so the community can also use our tools.
We also have plan of other tools and functionalities built on top of CarbonAI. As you can guess, we would rather develop them on top of a tool we deeply understand (since we developed it) than going into the details of someone else's.

**Comment by benoit-cty** [comment]
"we would rather develop them on top of a tool we deeply understand" => We could help you understand Code Carbon and it would be easy for you as it include what you already do. In the long term it's a win-win, you could always do you own fork at any time.
You will benefit of stronger power measurement, API server that handle different level of aggregation, web Dashboard with SSO, and so on... If you change your mind we are a bunch of french developers doing weekly meeting in french ;)

**Comment by MarionCoutarel** [comment]
Hello,
As a CodeCarbon contributor, I fear that maintaining two/three different projects is a waste of ressources as I'm sure we can benefit from one an other. 
In the mean time, "competition" can bring creativity so I hope this would be for the best in the end. 
Wish you the best for this project. 
I'll keep an eye on it as I'm sure you'll do on CodeCarbon .

As @benoit-cty said your more than welcome to come and have a chat with us on one of our weekly meeting

**Comment by Neyri** [comment]
I will now close the issue as an answer was provided.
